// Generated by: supabase gen types typescript --local
// Re-run with: pnpm --filter @sehatvault/db generate
// Hand-crafted for migrations 0001–0004; regenerate after each new migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      app_user: {
        Row: {
          id: string
          email: string | null
          locale: string
          elder_mode: boolean
          app_lock_hash: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          locale?: string
          elder_mode?: boolean
          app_lock_hash?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          locale?: string
          elder_mode?: boolean
          app_lock_hash?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_user_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      family: {
        Row: {
          id: string
          owner_user_id: string
          name: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_user_id: string
          name?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_user_id?: string
          name?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "family_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "app_user"
            referencedColumns: ["id"]
          },
        ]
      }
      health_record: {
        Row: {
          id: string
          member_id: string
          family_id: string
          type: Database["public"]["Enums"]["record_type"]
          source: Database["public"]["Enums"]["record_source"]
          file_object_key: string | null
          page_count: number | null
          record_date: string | null
          facility: string | null
          doctor: string | null
          title: string | null
          summary: string | null
          summary_hi: string | null
          ocr_status: Database["public"]["Enums"]["ocr_status"]
          ocr_confidence: number | null
          extracted: Json | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          member_id: string
          family_id: string
          type?: Database["public"]["Enums"]["record_type"]
          source?: Database["public"]["Enums"]["record_source"]
          file_object_key?: string | null
          page_count?: number | null
          record_date?: string | null
          facility?: string | null
          doctor?: string | null
          title?: string | null
          summary?: string | null
          summary_hi?: string | null
          ocr_status?: Database["public"]["Enums"]["ocr_status"]
          ocr_confidence?: number | null
          extracted?: Json | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          member_id?: string
          family_id?: string
          type?: Database["public"]["Enums"]["record_type"]
          source?: Database["public"]["Enums"]["record_source"]
          file_object_key?: string | null
          page_count?: number | null
          record_date?: string | null
          facility?: string | null
          doctor?: string | null
          title?: string | null
          summary?: string | null
          summary_hi?: string | null
          ocr_status?: Database["public"]["Enums"]["ocr_status"]
          ocr_confidence?: number | null
          extracted?: Json | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "health_record_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "member_profile"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "health_record_family_id_fkey"
            columns: ["family_id"]
            isOneToOne: false
            referencedRelation: "family"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "health_record_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "app_user"
            referencedColumns: ["id"]
          },
        ]
      }
      member_profile: {
        Row: {
          id: string
          family_id: string
          display_name: string
          relationship: string | null
          dob: string | null
          sex: Database["public"]["Enums"]["sex_type"]
          blood_group: string | null
          allergies: string[]
          chronic_conditions: string[]
          emergency_contact: Json | null
          abha_id: string | null
          photo_key: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          family_id: string
          display_name: string
          relationship?: string | null
          dob?: string | null
          sex?: Database["public"]["Enums"]["sex_type"]
          blood_group?: string | null
          allergies?: string[]
          chronic_conditions?: string[]
          emergency_contact?: Json | null
          abha_id?: string | null
          photo_key?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          family_id?: string
          display_name?: string
          relationship?: string | null
          dob?: string | null
          sex?: Database["public"]["Enums"]["sex_type"]
          blood_group?: string | null
          allergies?: string[]
          chronic_conditions?: string[]
          emergency_contact?: Json | null
          abha_id?: string | null
          photo_key?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "member_profile_family_id_fkey"
            columns: ["family_id"]
            isOneToOne: false
            referencedRelation: "family"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      auth_family_ids: {
        Args: Record<PropertyKey, never>
        Returns: string[]
      }
    }
    Enums: {
      ocr_status: "pending" | "processing" | "done" | "needs_review" | "failed" | "manual"
      record_source: "manual" | "upload" | "whatsapp" | "abdm" | "lab_push"
      record_type: "prescription" | "lab_report" | "scan" | "discharge" | "vaccination" | "bill" | "other"
      sex_type: "male" | "female" | "other" | "unknown"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never
